image: rust:latest

variables:
  REPO_NAME: gitlab.com/ufoot/vclock

before_script:
  - rustc --version
  - cargo --version
  - echo $CI_BUILD_REF
  - echo $CI_PROJECT_DIR

stages:
  - build
  - test

build:
  stage: build
  script:
    - cargo build

release:
  stage: build
  script:
    - cargo build --release

test:
  stage: test
  script:
    - cargo test

test_serde:
  stage: test
  script:
    - cargo test --features=serde

test_bigint:
  stage: test
  script:
    - cargo test --features=bigint

bench:
  image: rustlang/rust:nightly
  stage: test
  script:
    - cd bench && cargo bench
